site:
  about:
    siteName: Feedback Tree
    siteDescription: A unidirectional architecture for Android

Editorial:
  primaryColor: '#ffc66d'
  legacySearch: false
  avatar: 'assets/media/logo.png'
  social:
    github: 'eliekarouz/FeedbackTree'
  metaComponents:
    - type: 'orchidSearch'
  menu:
    - type: 'wikiSections'
      asSubmenu: false

    - type: 'page'
      itemId: 'Changelog'

    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'

kotlindoc:
  homePagePermalink: ':moduleGroup/:module'
  sourcePagePermalink: ':moduleType/:module/:sourceDocPath'
  sourceDirs:
    - '../../../../feedbacktree/src/main/java'

allPages:
  metaComponents:
    - type: 'prism'
      githubTheme: 'darcula'
      languages:
        - 'java'
        - 'kotlin'
        - 'yaml'
        - 'groovy'

wiki:
  sections:
    - key: 'tutorials'
      title: 'Tutorials'
    - key: 'howtoguides'
      title: 'How-To Guides'
    - key: 'reference'
      title: 'Reference'

sitemap:
  useRobots: true
  useSitemaps: true


services:
  publications:
    stages:
      - type: githubPages
        branch: gh-pages
        username: 'eliekarouz'
        repo: 'FeedbackTree'